version: '3.0'

services:
  book-api:
    env_file: .env
    container_name: book-api
    build:
      context: .
    ports:
      - 8000:3000
    links:
      - db:postgres
      - redis:redis
    profiles:
      - prod
  book-api-dev:
    env_file: .env
    container_name: book-api
    build:
      context: .
    command: sh -c "yarn && yarn start:dev"
    ports:
      - 8000:3000
    links:
      - db:postgres
      - redis:redis
    volumes:
      - .:/workspace
    profiles:
      - dev
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./migrations:/docker-entrypoint-initdb.d/
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
volumes:
  db-data: null
  rabbitmq-data: null
  rabbitmq-logs: null
