name: GitHub Actions Demo
on: [push]
jobs:
  workflow:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    container:
      image: node:14.15.0-alpine3.12
    steps:
      - name: Copy repository
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install --immutable
      - name: Lint code
        run: yarn lint
      - name: Run tests
        run: yarn test
     
